spring.application.name=ecovolt360

# Ativa o console web do H2
spring.h2.console.enabled=true

# Define o caminho de acesso (opcional, /h2-console é o padrão)
spring.h2.console.path=/h2-console

# Mantém os dados visíveis e o banco em memória ativo durante a execução
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=